name: Build and Deploy Feature artifacts

on:
  push:
    branches:    
      - 'feat/**'

env:
  CI: true
  NODE_ENV: "develop"

jobs:
  feat-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Artifacts
        env:
          BUCKET: ${{ secrets.BUCKET }}
          STORAGE_URL: ${{ secrets.STORAGE_URL }}
          STORAGE_KEY: ${{ secrets.STORAGE_KEY }}
        run: |
          wget https://github.com/websublime/sublime-cli/releases/download/v0.0.3/sublime-v0.0.3-linux-amd64.tar.gz
          tar -xf sublime-v0.0.1-linux-amd64.tar.gz sublime
          chmod +x sublime
          ./sublime action --kind branch --bucket "$BUCKET" --url "$STORAGE_URL" --key "$STORAGE_KEY" --env "$NODE_ENV"

#      - name: Supabase artifacts
#        uses: websublime/supabase-assets@v0.0.5
#        with:
#          url: ${{ secrets.SUPABASE_URL }}
#          key: ${{ secrets.SUPABASE_SECRET }}
#          folder: packages/ws-ui-header/dist/
#          bucket: ${{ secrets.SUPABASE_BUCKET }}
#          destiny: ws-ui-header-${{ github.sha }}-SNAPSHOT/
