name: Build Binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo git describe --tags $(git rev-list --tags --max-count=1))

    - name: Vendor
      run: go mod vendor

    - name: Build
      run: make build

    - name: Test
      run: go test -v ./...
