name: Build Binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set APP_VERSION env
      run: |
        echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
        echo $GITHUB_ENV
        echo $APP_VERSION

    - name: Vendor
      run: go mod vendor

    - name: Build
      run: make build

    - name: Test
      run: go test -v ./...
